PLAYER_CHARACTER_SHEET = {
    "attributes": {
        "stre": 2,
        "dex": 4,
        "sta": 2,
        "cha": 5,
        "man": 5,
        "app": 1,
        "per": 1,
        "inte": 3,
        "wits": 5
    },
    "epic_attributes": {
        "epic_stre": 0,
        "epic_dex": 1,
        "epic_sta": 0,
        "epic_cha": 3,
        "epic_man": 3,
        "epic_app": 0,
        "epic_per": 0,
        "epic_inte": 0,
        "epic_wits": 1
    },
    "player_id": 382348220405383171,
    "name": "Bob 'Steve' Roberts",
    "stre_mod": 0,
    "dex_mod": 0,
    "sta_mod": 0,
    "cha_mod": 0,
    "man_mod": 0,
    "app_mod": 0,
    "per_mod": 0,
    "inte_mod": 0,
    "wits_mod": 0,
    "epic_stre_mod": 0,
    "epic_dex_mod": 0,
    "epic_sta_mod": 0,
    "epic_cha_mod": 0,
    "epic_man_mod": 0,
    "epic_app_mod": 0,
    "epic_per_mod": 0,
    "epic_inte_mod": 0,
    "epic_wits_mod": 0,
    "legend": 3,
    "xp": 0,
    "xp_spent": 0,
    "legend_points_total": 0,
    "legend_points_current": 0,
    "willpower_total": 0,
    "willpower_current": 0,
    "virtues": [3,2,0,0],
    "inventory": [],
    "knacks": ["God's Honest", "Blurt It Out", "Divine Figurehead", "Cat's Grace", "Social Chameleon"],
    "boons": ["Animal Communication", "Warrior Ideal", "Penetrating Glare", "Smoking Mirror"],
    "relics": [["Divine Bazooka", 1], ["Bodkin", 1],],
    "creatures": [["Nala the Flying Dog", 5],],
	"movement": {
		"dash": 0,
		"move": 0,
		"climb": 0,
        "swim": 2,
		"jump": {
			"horizontal": 0,
			"vertical": 0
		}
	},
    "join_battle": 0,
    "combat": { # 1: speed, 2: damage, 3: def, 4: dv minus
	    "bazooka": [10, "35L", 0, 0],
	    "bodkin": [3, "6L", 2, 0],
        "melee": [0, 0, 0, 0],
        "range": [0, 0, 0, 0],
        "dodge": [7, 0, 0, 0],
        "parry": [5, 0, 0, 0],
        "coordattack": [5, 0, 0, -2],
        "dash": [3, 0, 0, -2],
        "aim": [3, 0, 0, -1],
        "guard": [3, 0, 0, 0],
        "move": [0, 0, 0, 0],
        "grapple": [0, 0, 0, 0],
        "inactive": [5, 0, 0, 0],
    },
    "health": {
        "bludgeon": 0,
        "lethal": 0,
        "aggrevated": 0
    },
    "abilities":    {
        "academics": 0,
        "animal_ken": 3,
        "art": 0,
        "athletics": 4,
        "awareness": 0,
        "brawl": 3,
        "command": 0,
        "control": 1,
        "craft": 4,
        "empathy": 0,
        "fortitude": 2,
        "integrity": 0,
        "investigation": 0,
        "larceny": 0,
        "marksmanship": 5,
        "medicine": 0,
        "melee": 0,
        "occult": 1,
        "presence": 5,
        "politics": 0,
        "science": 0,
        "stealth": 2,
        "survival": 0,
        "thrown": 0
    },
    "armor": {
        "bludgeon": 4,
        "lethal": 2,
        "aggrevated": 0
    },
    "soak": {
        "bludgeon": 3,
        "lethal": 2,
        "aggrevated": 0
    },
    "armor_mod": {
        "bludgeon": 0,
        "lethal": 0,
        "aggrevated": 0
    },
    "soak_mod": {
        "bludgeon": 0,
        "lethal": 0,
        "aggrevated": 0
    }
}