PLAYER_CHARACTER_SHEET = {
	"attributes": {
		"stre": 0,
		"dex": 0,
		"sta": 0,
		"cha": 0,
		"man": 0,
		"app": 0,
		"per": 0,
		"inte": 0,
		"wits": 2
	},
	"epic_attributes": {
		"epic_stre": 0,
		"epic_dex": 0,
		"epic_sta": 0,
		"epic_cha": 0,
		"epic_man": 0,
		"epic_app": 0,
		"epic_per": 0,
		"epic_inte": 0,
		"epic_wits": 5
	},
	"player_id": 433097995832000513,
    "name": "Ferdiad",
	"stre_mod": 0,
	"dex_mod": 0,
	"sta_mod": 0,
	"cha_mod": 0,
	"man_mod": 0,
	"app_mod": 0,
	"per_mod": 0,
	"inte_mod": 0,
	"wits_mod": 0,
	"epic_stre_mod": 0,
	"epic_dex_mod": 0,
	"epic_sta_mod": 0,
	"epic_cha_mod": 0,
	"epic_man_mod": 0,
	"epic_app_mod": 0,
	"epic_per_mod": 0,
	"epic_inte_mod": 0,
	"epic_wits_mod": 0,
	"xp": 0,
	"xp_spent": 0,
    "legend": 3,
	"legend_points_total": 0,
	"legend_points_current": 0,
	"willpower_total": 0,
	"willpower_current": 0,
	"virtues": [0,0,0,0],
	"inventory": [],
	"knacks": [],
	"boons": [],
	"relics": [],
	"creatures": [],
	"movement": {
		"dash": 0,
		"move": 0,
		"climb": 0,
		"swim": 2,
		"jump": {
			"horizontal": 0,
			"vertical": 0
		}
	},
	"join_battle": 0,
	"combat": { # 1: speed, 2: damage, 3: def, 4: dv minus
		"melee": [0, 0, 0, 0],
		"range": [0, 0, 0, 0],
		"dodge": [0, 0, 0, 0],
		"parry": [0, 0, 0, 0],
		"coordattack": [5, 0, 0, -2],
		"dash": [3, 0, 0, -2],
		"aim": [3, 0, 0, -1],
		"guard": [3, 0, 0, 0],
		"move": [0, 0, 0, 0],
		"grapple": [0, 0, 0, 0],
		"inactive": [5, 0, 0, 0],
		"dodge_dv" : 0,
		"parry_dv" : 0,
	},
	"health": {
		"bludgeon": 0,
		"lethal": 0,
		"aggrevated": 0
	},
	"abilities":	{
		"academics": 0,
		"animal_ken": 0,
		"art": 0,
		"athletics": 0,
		"awareness": 3,
		"brawl": 0,
		"command": 0,
		"control": 0,
		"craft": 0,
		"empathy": 0,
		"fortitude": 0,
		"integrity": 0,
		"investigation": 0,
		"larceny": 0,
		"marksmanship": 0,
		"medicine": 0,
		"melee": 0,
		"occult": 0,
		"presence": 0,
		"politics": 0,
		"science": 0,
		"stealth": 0,
		"survival": 0,
		"thrown": 0
	},
	"armor": {
		"bludgeon": 0,
		"lethal": 0,
		"aggrevated": 0
	},
	"soak": {
		"bludgeon": 0,
		"lethal": 0,
		"aggrevated": 0
	},
	"armor_mod": {
		"bludgeon": 0,
		"lethal": 0,
		"aggrevated": 0
	},
	"soak_mod": {
		"bludgeon": 0,
		"lethal": 0,
		"aggrevated": 0
	}
}